CREATE TABLE `TB_APPLICATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `ENDDATE` datetime(6) DEFAULT NULL,
  `GPUCOUNT` int(11) DEFAULT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `IMAGENAME` varchar(255) DEFAULT NULL,
  `LIMITCPU` varchar(255) DEFAULT NULL,
  `LIMITMEM` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PORT` int(11) DEFAULT NULL,
  `REQUESTCPU` varchar(255) DEFAULT NULL,
  `REQUESTMEM` varchar(255) DEFAULT NULL,
  `STARTDATE` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_CODE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `ARGUMENTS` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `FULLPATH` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `NODETYPE` varchar(255) DEFAULT NULL,
  `PATH` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_ENV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_IMAGE` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `component_execute` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `execute_option` varchar(255) DEFAULT NULL,
  `imageName` varchar(255) DEFAULT NULL,
  `image_authority` varchar(255) DEFAULT NULL,
  `image_repository_type` varchar(255) DEFAULT NULL,
  `log` varchar(255) DEFAULT NULL,
  `node_type` varchar(255) DEFAULT NULL,
  `ports` int(11) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `tag` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `IMAGE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_NODE` (
  `DTYPE` varchar(31) NOT NULL,
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `nodeIp` varchar(255) DEFAULT NULL,
  `nodeName` varchar(255) DEFAULT NULL,
  `gpuCount` int(11) DEFAULT NULL,
  `gpuType` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_NODE_ASSIGN` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `endDate` datetime(6) DEFAULT NULL,
  `startDate` datetime(6) DEFAULT NULL,
  `node_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_PROJECT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `ENDDATE` datetime(6) DEFAULT NULL,
  `GPUCOUNT` int(11) DEFAULT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `IMAGENAME` varchar(255) DEFAULT NULL,
  `LIMITCPU` varchar(255) DEFAULT NULL,
  `LIMITMEM` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PORT` int(11) DEFAULT NULL,
  `REQUESTCPU` varchar(255) DEFAULT NULL,
  `REQUESTMEM` varchar(255) DEFAULT NULL,
  `STARTDATE` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `NODE_PORT` int(11) DEFAULT NULL,
  `GPUTYPE` varchar(255) DEFAULT NULL,
  `code_ID` bigint(20) DEFAULT NULL,
  `imageEntity_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_PROJECT_ARGS` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `args` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_PROJECT_CMD` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cmd` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_PROJECT_NODE` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `node_id` bigint(20) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_PROJECT_TOOL` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `port` int(11) NOT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  `tool_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TB_TOOL` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `execute` varchar(255) DEFAULT NULL,
  `toolName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
