CREATE TABLE IF NOT EXISTS `TB_APPLICATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `ENDDATE` datetime(6) DEFAULT NULL,
  `GPUCOUNT` int(11) DEFAULT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `IMAGENAME` varchar(255) DEFAULT NULL,
  `LIMITCPU` varchar(255) DEFAULT NULL,
  `LIMITMEM` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PORT` int(11) DEFAULT NULL,
  `REQUESTCPU` varchar(255) DEFAULT NULL,
  `REQUESTMEM` varchar(255) DEFAULT NULL,
  `STARTDATE` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_ENV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PROJECT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `ENDDATE` datetime(6) DEFAULT NULL,
  `GPUCOUNT` int(11) DEFAULT NULL,
  `IMAGE` varchar(255) DEFAULT NULL,
  `IMAGENAME` varchar(255) DEFAULT NULL,
  `LIMITCPU` varchar(255) DEFAULT NULL,
  `LIMITMEM` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PORT` int(11) DEFAULT NULL,
  `REQUESTCPU` varchar(255) DEFAULT NULL,
  `REQUESTMEM` varchar(255) DEFAULT NULL,
  `STARTDATE` datetime(6) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `NODE_PORT` int(11) DEFAULT NULL,
  `GPUTYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_GPU` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `gpuCount` int(11) NOT NULL,
  `gpuIndex` int(11) NOT NULL,
  `nodeIp` varchar(255) DEFAULT NULL,
  `nodeName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_GPU_ASSIGN` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `endDate` datetime(6) DEFAULT NULL,
  `startDate` datetime(6) DEFAULT NULL,
  `gpuNode_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PROJECT_ARGS` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `args` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PROJECT_CMD` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cmd` varchar(255) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PROJECTGPU` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `CONSTRUCTOR` varchar(255) DEFAULT NULL,
  `MOD_DATE` datetime(6) DEFAULT NULL,
  `MODIFIER` varchar(255) DEFAULT NULL,
  `REG_DATE` datetime(6) DEFAULT NULL,
  `gpuNode_id` bigint(20) DEFAULT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_PROJECT_TOOL` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `port` int(11) NOT NULL,
  `project_ID` bigint(20) DEFAULT NULL,
  `tool_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TB_TOOL` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `execute` varchar(255) DEFAULT NULL,
  `toolName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
