apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uyuni-suite-prod

resources:
- ../../base/deployments
- ../../base/services
- ../../base/configmaps
- volumes

secretGenerator:
- files:
  - config
  name: kube-config

patchesStrategicMerge:
- core-deployment-env.yaml
- batch-deployment-env.yaml
- noti-deployment-env.yaml

images:
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-batch
  newName: xiilab/uyuni-manager-batch
  newTag: 0.3.1-stag
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-core
  newName: xiilab/uyuni-manager-core
  newTag: 0.3.1-stag
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-noti
  newName: xiilab/uyuni-manager-noti
  newTag: 0.3.1-stag
- name: harbor.xiilab.com/uyuni-suite/uyuni-suite-frontend
  newName: xiilab/uyuni-suite-frontend
  newTag: 0.3.5-stag
