apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-batch
spec:
  selector:
    matchLabels:
      app: uyuni-manager-batch
  template:
    metadata:
      labels:
        app: uyuni-manager-batch
    spec:
      hostAliases:
      - ip: "192.168.1.237" # host change
        hostnames:
        - "bigdata-car.kr" # host change
      containers:
      - name: uyuni-manager-batch
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://bigdata-car.kr:32080/auth
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite-katech
