apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
      hostAliases:
      - ip: "192.168.1.237"
        hostnames:
        - "bigdata-car.kr" # host change
      containers:
      - name: uyuni-manager-core
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://bigdata-car.kr:32080/auth # host change
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite-katech
        - name: UYUNIHOST
          value: 192.168.1.238 # host change
