apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-suite-frontend
spec:
  selector:
    matchLabels:
      app: uyuni-suite-frontend
  template:
    metadata:
      labels:
        app: uyuni-suite-frontend
    spec:
      containers:
      - name: uyuni-suite-frontend
        env:
        - name: REACT_APP_NAME
          value: 'Uyuni Suite'
        - name: REACT_APP_BACKEND_HOST
          value: http://uyuni.bigdata-car.kr
        - name: REACT_APP_BASE_URL
          value: api/v1
        - name: REACT_APP_KEYCLOAK_HOST
          value: http://uyuni.bigdata-car.kr
        - name: REACT_APP_KEYCLOAK_URL
          value: http://uyuni.bigdata-car.kr/auth/
        - name: REACT_APP_KEYCLOAK_REALM
          value: uyuni
        - name: REACT_APP_KEYCLOAK_CLIENT_ID
          value: uyuni
        - name: REACT_APP_SSE_HOST
          value: http://uyuni.bigdata-car.kr

