apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-batch
spec:
  selector:
    matchLabels:
      app: uyuni-manager-batch
  template:
    metadata:
      labels:
        app: uyuni-manager-batch
    spec:
      hostAliases:
      - ip: "192.168.2.150"
        hostnames:
        - "dev.uyuni-suite.xiilab.com"
      containers:
      - name: uyuni-manager-batch
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://dev.uyuni-suite.xiilab.com/auth
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite-develop
      imagePullSecrets:
      - name: regcred
