apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
#      hostAliases:
#      - ip: "192.168.2.150"
#        hostnames:
#        - "uyuni-suite.xiilab.com"
      containers:
      - name: uyuni-manager-core
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://uyuni-suite.xiilab.com:32080/auth
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite
        - name: UYUNIHOST
          value: 192.168.1.235
