apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-suite-frontend
spec:
  selector:
    matchLabels:
      app: uyuni-suite-frontend
  template:
    metadata:
      labels:
        app: uyuni-suite-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: uyuni-suite-frontend
        env:
        - name: REACT_APP_KEYCLOAK_REALM
          value: uyuni
        - name: REACT_APP_KEYCLOAK_CLIENT_ID
          value: uyuni
        - name: REACT_APP_KEYCLOAK_URL
          value: http://uyuni-suite.xiilab.com:40080/auth
