apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-batch
spec:
  selector:
    matchLabels:
      app: uyuni-manager-batch
  template:
    metadata:
      labels:
        app: uyuni-manager-batch
    spec:
      containers:
      - name: uyuni-manager-batch
        image: harbor.xiilab.com/uyuni-suite/uyuni-manager-batch:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: kube-config
          mountPath: "/root/.kube"
          readOnly: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config
