apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
      containers:
      - name: uyuni-manager-core
        image: harbor.xiilab.com/uyuni-suite/uyuni-manager-core:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: kube-config
          mountPath: "/root/.kube"
          readOnly: true
      
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config
