apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
      containers:
      - name: uyuni-manager-core
        image: harbor.xiilab.com/uyuni-suite/uyuni-manager-core:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: mig-profile-path
          value: /root/migProfile/migProfile.json
        volumeMounts:
        - name: kube-config
          mountPath: "/root/.kube"
          readOnly: true
        - name: uyuni-pvc
          mountPath: "/root/uyuni"
        - name: migprofilevolume
          mountPath: '/root/migProfile'
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config
      - name: uyuni-pvc
        persistentVolumeClaim:
          claimName: uyuni-pvc
      - name: migprofilevolume
        configMap:
          name: migconfigmap
