apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-monitor
spec:
  selector:
    matchLabels:
      app: uyuni-manager-monitor
  template:
    metadata:
      labels:
        app: uyuni-manager-monitor
    spec:
      containers:
      - name: uyuni-manager-monitor
        image: harbor.xiilab.com/uyuni-suite/uyuni-manager-monitor:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regcred
