apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
      hostAliases:
      - ip: "10.10.15.119"
        hostnames:
        - "gpu.seoultech.ac.kr"
      containers:
      - name: uyuni-manager-core
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://gpu.seoultech.ac.kr:32080/auth
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite
        - name: UYUNIHOST
          value: 10.10.15.119
      nodeSelector:
        kubernetes.io/hostname: gpu-mgmt
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
