apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-suite-frontend
spec:
  selector:
    matchLabels:
      app: uyuni-suite-frontend
  template:
    metadata:
      labels:
        app: uyuni-suite-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: gpu-mgmt
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"            
