apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-manager-core
spec:
  selector:
    matchLabels:
      app: uyuni-manager-core
  template:
    metadata:
      labels:
        app: uyuni-manager-core
    spec:
      hostAliases:
      - ip: "10.10.10.37"
        hostnames:
        - "dev.bigdata-car.kr" # host change
      containers:
      - name: uyuni-manager-core
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: KEYCLOAK_REALM
          value: uyuni
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://211.218.247.36:23080/auth # host change
        - name: KEYCLOAK_RESOURCE
          value: uyuni
        - name: K8S_NAMESPACE
          value: uyuni-suite-katech
        - name: UYUNIHOST
          value: 211.218.247.36:23080 # host change
      nodeSelector:
        kubernetes.io/hostname: master03
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"      
