apiVersion: v1
kind: PersistentVolume
metadata:
  name: uyuni-project-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: uyuni-project
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:
    server:
