apiVersion: v1
kind: PersistentVolume
metadata:
  name: katech-dataset-pv-dev
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: katech-dataset-dev
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /DATA_SET/USER
    server: 10.10.20.59
