apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uyuni-suite-katech

resources:
- ../../base/deployments
- ../../base/services
- ../../base/configmaps
- volumes
- postgres-keycloak-sync.yaml 

secretGenerator:
- name: kube-config
  files:
  - config
- name: regcred
  files:
  - .dockerconfigjson
  type: kubernetes.io/dockerconfigjson  
- files:
    - tls.crt=tls/unified.bigdata-car.kr.crt
    - tls.key=tls/key.unencrypted.pem
  name: bigdata-tls
  type: kubernetes.io/tls  

patchesStrategicMerge:
- core-deployment-env.yaml
- batch-deployment-env.yaml
- noti-deployment-env.yaml
- frontend-deployment-env.yaml
- mariadb-deployment-env.yaml
  #- ingress-tls.yaml

patchesJson6902:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: ingress-uyuni-suite

images:
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-batch
  newName: xiilab/uyuni-manager-batch
  newTag: 0.85-katech
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-core
  newName: xiilab/uyuni-manager-core
  newTag: 0.85-katech
- name: harbor.xiilab.com/uyuni-suite/uyuni-manager-noti
  newName: xiilab/uyuni-manager-noti
  newTag: 0.85-katech
- name: harbor.xiilab.com/uyuni-suite/uyuni-suite-frontend
  # newName: xiilab/front-end
  # newTag: "0.1.7"
  newName: xiilab/uyuni-suite-frontend
  newTag: "0.137-katech"
- name: xiilab/katech-postgres-daemon:latest
  newName: xiilab/katech-postgres-daemon
  newTag: "0.8"
