apiVersion: v1
kind: PersistentVolume
metadata:
  name: uyuni-suite-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: uyuni-suite
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /kube_storage/uyuni-data
    server: 192.168.2.27
